### ISSUE TITLE
How to specify color

### ISSUE THREAD

**Issue by dibs439** [mcastorina/graph-cli#28]
I am trying to generate a comparative bar diagram where I wanted to use custom color codes. Please suggest how to specify the same option in command line.

I am using the following but it does not work:

sudo /var/www/html/graph-cli/graph $FILE --bar --width 0.05 --figsize 634x117 --title 'Solar Production vs Energy Consumption' --offset=-0.05,0.05 --color=246,180,190,0.2, 225, 7, 47, 0.8 -o "$OUTPUT_DIR$basename.png"

**Comment by mcastorina** [comment]
Hi, the `--color` argument gets passed directly to matplotlib and can take hex colors such as `#ff0000` for red.

Are you trying to use RGBA colors? If so try this:

```
--color='#f6b4be,#e1072f'
```

**Comment by mcastorina** [comment]
Any of these colors should work as well
https://matplotlib.org/3.1.0/gallery/color/named_colors.html

**Comment by dibs439** [comment]
Thanks you so much for your prompt response. It works.
