### ISSUE TITLE
Adjusting font and graph size to fit in a specific dimension

### ISSUE THREAD

**Issue by dibs439** [mcastorina/graph-cli#30]
Dear Author,

I have been able to generate charts with help from your end previously. At present the graph is generating at the height-width specific in the command. However, some part of the image is getting cut-off.  And overall look and feel needs some adjustment. The current and expected output is attached for your reference. I would like the some inputs regarding:

1. How to make the bars thinner lie in the expected.png
2. Currently both bars are not showing side-by-side but they are overlapping.
3. How to make the legends smaller
4. Y-axis should show more steps.

I am using the following command:

sudo graph source.csv --bar --width 0.4 --title 'Title' --offset 0.2,0.2 --color='#f6b4be,#e1072f' --fontsize=12 --label-fontsize=8 --figsize=634x117 --xlabel-fontsize=10 --ylabel-fontsize=8 -o dest.png

Any inputs on any of the points will be highly appreciated.

![expected](https://user-images.githubusercontent.com/202687/85176190-dfee5b00-b296-11ea-8c51-86e1756a74f3.png)
![current](https://user-images.githubusercontent.com/202687/85176192-e11f8800-b296-11ea-8bdf-878c5c6dcef7.png)

**Comment by dibs439** [comment]
Sir any thoughts on this?

**Comment by mcastorina** [comment]
Yes, creating bar graphs with the tool is not very intuitive (has been on my todo list for awhile)

1. `--width` controls the bar width
2. You need to set the offset manually to have both bars show; generally one is negative the other is positive and they should be half the `--width` value
    * For your example, it would be `--offset=-0.2,0.2`
3. No support for this yet -- https://github.com/mcastorina/graph-cli/issues/18
4. `--yrange min:max` to control the start and end values of the y-axis; `--yscale scale` for the scaling (in other words.. `--yscale 500` will draw a line every 500 y units

**Comment by mcastorina** [comment]
A workaround for all of the sizing problems would be to remove `--figsize`, then use [imagemagick](https://imagemagick.org/index.php) to resize the final image to fit your needs.

**Comment by mcastorina** [comment]
I have pushed an update for 3. You should be able to use `--fontsize` to set the global font size. This is in version 0.1.6

**Comment by dibs439** [comment]
The issue has been resolved thanks a lot!
