### ISSUE TITLE
Error when running from outside of the graph-cli directory

### ISSUE THREAD

**Issue by dibs439** [mcastorina/graph-cli#31]
Sir,

When I run the graph command from another directory it throws following error. For example my command is:
../graph-cli/graph samples/sine.csv -o sine.png

Output is:

Traceback (most recent call last):
  File "../graph-cli/graph", line 5, in <module>
    import options
ImportError: No module named options

Thanks in advance for your consideration.

**Comment by mcastorina** [comment]
The graph script is intended for local development only. Please install via pip and the executable should be in a directory in your PATH

```
python3 -m pip install graph-cli
```

**Comment by dibs439** [comment]
Hello Miccah,

I did that and when I run this from inside my laravel script it does not produce any output meaning it does not create the files from CSV as desired. Any suggestions on your end?

Thanks

**Comment by mcastorina** [comment]
Perhaps it's a permission issue.

**Comment by dibs439** [comment]
Thanks a lot. I will check.

**Comment by dibs439** [comment]
Hi Miccah,

Is there a way to run this script in the form of an REST API which can be executed from Postman or a Browser (For a GET Request).

Much appreciate your help.

**Comment by mcastorina** [comment]
Maybe #32 is related. Try updating your graph-cli version to the latest (0.1.7) and see if your laravel script works.

**Comment by dibs439** [comment]
Thanks it worked!
