### ISSUE TITLE
How to read from stdin?

### ISSUE THREAD

**Issue by lodenrogue** [mcastorina/graph-cli#34]
Thank you for creating this project. I want to be able to read from stdin so I can do something like:

generate_csv_command | graph -o output.png

**Comment by mcastorina** [comment]
Hi! You can use `-` in place of a filename to graph from stdin:

```
cat samples/sine.csv | graph - -o sine.png
```

**Comment by lodenrogue** [comment]
Confirmed working. Thank you!
