### ISSUE TITLE
Disable exponent notation

### ISSUE THREAD

**Issue by wtfpeter** [mcastorina/graph-cli#36]
When working with large numbers for values, the axes automatically get exponentiated (is that correct? Not a math guy, sorry if that is wrong). 
What I mean is the notation of e.g. 1e6 for 1'000'000. 
I would like to be able to disable this, to display the values in 'clear' without exponent.

**Comment by mcastorina** [comment]
Could you please provide a sample csv, so I can recreate it? This is happening automatically when the CSV is read in through pandas, so it may take some work to get it right.

Thanks!

**Comment by wtfpeter** [comment]
Sure, here you go! Nothing fancy..

"#","Col1","Col2"
"27","108431","930451"
"26","126892","1001895"
"25","136731","978702"
"24","136706","978444"
"23","132377","978806"
"22","141134","980492"
"21","177306","975811"
"20","175844","973934"
"19","176123","972611"
"18","179297","955741"
"17","230613","921516"
"16","229046","808653"
"15","228734","807206"
"14","228721","807264"
"13","212163","807706"
"12","213634","808874"
"11","216201","745381"
"10","217655","741734"
"9","178666","739913"
"8","182155","776331"
"7","188234","755435"
"6","185513","955713"
"5","183261","955664"
"4","183057","955225"
"3","153884","931541"
"2","153416","898564"
"1","499484","897975"

**Comment by mcastorina** [comment]
Fixed in 1bef4e46f240cb8ef2531578bf19be4f85613740

Any numbers between `10e-3` and `10e9` will not be in exponent format.

I think those a reasonable defaults, but I'll work on adding a flag for user-control.

**Comment by wtfpeter** [comment]
> 
> 
> Fixed in [1bef4e4](https://github.com/mcastorina/graph-cli/commit/1bef4e46f240cb8ef2531578bf19be4f85613740), it will be included in the next release.
> 
> Any numbers between `10e-3` and `10e9` will not be in exponent format.
> 
> I think those are reasonable defaults, but I'll work on adding a flag for user control.

Thanks a lot, looking forward to the release! 
Those defaults work for my use cases, but I guess for more mathematical uses a config flag makes sense.

**Comment by mcastorina** [comment]
The `--exponent-range` flag has been added and included in `v0.1.8`.

Thanks for requesting this feature!
