### ISSUE TITLE
Selecting multiple columns for y

### ISSUE THREAD

**Issue by nodecentral** [mcastorina/graph-cli#38]
Hi

I have a csv full of different temperature data, is there a way I can choose a selection of columns to plot on the graph ? So far using the -y option I can only select one ?

````
graph home/pi/shared/test.csv -y 3 --ylabel Temp --output home/pi/shared/test.png

**Comment by nodecentral** [comment]
FYI, I’ve tried the following but neither worked.

````
graph home/pi/shared/test.csv -y 3 | graph home/pi/shared/test.csv -y 4 --ylabel Temp --title CabinTemp --figsize 1600x1000 --output home/pi/shared/test7.png
````

**Comment by nodecentral** [comment]
Think I’ve got it, this seems to do it..
````
graph home/pi/shared/feed.csv -y 9,10 --style='-.' --ylabel Temp --title CabinTemp --figsize 1600x1000 --output home/pi/shared/report.png

**Comment by mcastorina** [comment]
Glad you found a solution! Most parameters can accept multiple values (comma separated). For example if you wanted two different styles for each line, you could do `--style='-.','--'`.

For columns you can also specify the name instead of the number.
