### ISSUE TITLE
Graph with time on x-axis adds in day date without being supplied in csv file.

### ISSUE THREAD

**Issue by CaptainMidnight** [mcastorina/graph-cli#42]
Creating a graph with temperature data against time on the x-axis, the time information supplied within the csv file has no day date infomration but the resultant graph x-axis is prefixed with the day number in the format DD HH:MM not just as expected HH:MM.

The data supplied and graph command line creates the graph with incorrect x-axis labling.

`pi.csv`: -

```
x,y
21:28:49,36.5
21:28:54,35.5
21:28:59,35.5
21:29:04,36.0
21:29:09,35.5
21:29:14,37.0
21:29:19,36.5
21:29:24,35.0
21:29:29,36.0
21:29:34,36.0
21:29:49,43.3
21:29:59,44.3
21:30:09,45.7
21:30:19,45.7
21:30:29,45.2
21:30:39,47.2
21:30:49,46.7
21:30:59,45.7
21:31:09,46.7
21:31:19,47.2
21:31:29,46.7
21:31:39,47.2
21:31:49,47.7
21:31:59,48.2
21:32:09,47.7
21:32:19,48.2
21:32:29,48.2
21:32:39,47.7
21:32:49,48.7
21:32:59,49.1
21:33:09,49.1
21:33:19,48.7
21:33:29,48.7
21:33:39,48.7
21:33:50,49.6
21:34:00,49.6
21:34:10,49.1
21:34:20,49.1
21:34:30,49.1
21:34:40,49.1
21:34:50,50.1
21:35:00,50.1
21:35:10,49.1
21:35:20,50.1
21:35:30,50.1
21:35:40,50.6
21:35:50,50.1
21:36:00,50.6
21:36:10,49.6
21:36:20,49.6
21:36:25,42.8
21:36:30,42.3
21:36:35,40.9
21:36:40,40.9
21:36:45,40.9
21:36:50,41.8
21:36:55,40.4
21:37:00,39.9
21:37:05,40.4
21:37:10,39.9
```
Graph command line: -
```
graph pi.csv --title "CPU Heatsink Stress Test Result" --figsize 1000x500 --ylabel "Temp ('c)" --yrange 30:60 --xlabel "Time (min)" --legend "CPU Temp" --fontsize 8 --markersize 2 -o pi.png 
```

The erroneous prefix day date before the time is not found in the csv data file - therefore shouldn't exist as can clearly be seen on this resultant graph: -

![pi](https://user-images.githubusercontent.com/6299317/111068564-289f1180-84c1-11eb-8aa6-748322d1b5c8.png)

**Comment by mcastorina** [comment]
Thanks for opening an issue! The default time formatting is determined by how `pandas` parses the CSV. Currently there's no way to change how it's outputted, so I think a `--time-format-output` flag should be added so you can specify `%H:%M`

**Comment by CaptainMidnight** [comment]
> --time-format-output

Hi thanks for your quick reply, where are you suggesting that option can be added? Addiing to the graph command line inidicates it's an unrecognized argument: -

```
C:\python>graph pi.csv --title "CPU Heatsink Stress Test Result" --figsize 1000x500 --ylabel "Temp ('c)" --yrange 30:60 --xlabel "Time (HH:MM)" --legend "CPU Temp" --fontsize 8 --markersize 2 --time-format-output %H:%M -o pi.png
usage: graph [-h] [--xcol COL] [--ycol COL] [--legend LEGEND] [--color COLOR] [--style STYLE]
             [--fill] [--marker MARKER] [--width WIDTH] [--offset OFFSET]
             [--markersize MARKERSIZE] [--output FILE] [--time-format FORMAT] [--resample FREQ]
             [--sort] [--bar] [--barh] [--hist] [--hist-perc] [--bins BINS] [--bin-size BIN_SIZE]
             [--xlabel LABEL] [--xscale SCALE] [--xrange RANGE] [--ylabel LABEL] [--yscale SCALE]
             [--yrange RANGE] [--figsize SIZE] [--title TITLE] [--fontsize FONTSIZE]
             [--tick-fontsize TICK_FONTSIZE] [--label-fontsize LABEL_FONTSIZE]
             [--xtick-fontsize XTICK_FONTSIZE] [--xtick-angle XTICK_ANGLE]
             [--xtick-align XTICK_ALIGN] [--xlabel-fontsize XLABEL_FONTSIZE]
             [--ytick-fontsize YTICK_FONTSIZE] [--ytick-angle YTICK_ANGLE]
             [--ytick-align YTICK_ALIGN] [--ylabel-fontsize YLABEL_FONTSIZE] [--no-grid]
             [--grid GRID] [--grid-color GRID_COLOR] [--grid-alpha GRID_ALPHA]
             [--grid-width GRID_WIDTH] [--text TEXT] [--annotate ANNOTATE]
             [--exponent-range RANGE] [--chain]
             CSV
graph: error: unrecognized arguments: --time-format-output %H:%M
```

**Comment by mcastorina** [comment]
It doesn't exist yet :)

**Comment by CaptainMidnight** [comment]
Ah ok, but what does --time-format do?

**Comment by mcastorina** [comment]
`--time-format` lets you specify the time format in the CSV instead of guessing it. Guessing can take a long time, so telling the program what format it is in can make it faster.

I'll probably rename that flag to `--time-format-input`

**Comment by CaptainMidnight** [comment]
> `--time-format` lets you specify the time format in the CSV instead of guessing it. Guessing can take a long time, so telling the program what format it is in can make it faster.
> 
> I'll probably rename that flag to `--time-format-input`

Ok, so if I now use `--time-format %H:%M:%S` the graph is as before, but now each time listed on the x-axis has a prefix of `01 HH:MM` i.e 01 09:05 etc so it's changed from 14 to 01 (?)
![pi](https://user-images.githubusercontent.com/6299317/111068488-d4942d00-84c0-11eb-9eb1-180e6d4fa061.png)

**Comment by mcastorina** [comment]
My guess is that `pandas` doesn't find the date information in the CSV, so by default it uses today (the 14th). When specifying a datetime format it may default to 0s (aka `Jan 1, 1970`). Hence the "01" instead of "14".

All speculation :)

**Comment by CaptainMidnight** [comment]
I do understand this tool isn't probably a high priority project and appreciate what you have produced to date.

I've just adjusted my x-axis label to cover this quirky result ;o) otherwise I'd end up manually editing the .png file, which is just creating an unwanted additional step in the graph production process.
![pi](https://user-images.githubusercontent.com/6299317/111070231-8be07200-84c8-11eb-8c11-1b0ebefb068c.png)

**Comment by mcastorina** [comment]
Thanks for being considerate, but I should be able to implement this today. If you are interested, feel free to poke at the source yourself and make a PR.

I opened #43 for the new feature.

**Comment by CaptainMidnight** [comment]
Now working great with the new version [0.1.9](https://github.com/mcastorina/graph-cli/commit/60b3f3a386c5373105b272ea9f207b5cf623180a)

![pi](https://user-images.githubusercontent.com/6299317/111121059-17f3a780-8564-11eb-8888-50a71cb1fa2a.png)
