### ISSUE TITLE
Add ability to format displayed time

### ISSUE THREAD

**Issue by mcastorina** [mcastorina/graph-cli#43]
- [x] `--time-format-output` flag should be added
- [x] `--time-format` flag should be renamed to `--time-format-input`

**Comment by mcastorina** [comment]
Implemented in f6bf3aa19cc928345079878558ebfdcefdafb936 and available in version `v0.1.9`

**Comment by mcastorina** [comment]
@CaptainMidnight fyi

**Comment by CaptainMidnight** [comment]
@mcastorina thanks works a treat

![pi](https://user-images.githubusercontent.com/6299317/111119283-d8c45700-8561-11eb-943b-fc3829585e86.png)
