### ISSUE TITLE
allow input csv from stdin

### ISSUE THREAD

**Issue by mattvenn** [mcastorina/graph-cli#46]
would be a nice addition to be able to pipe the data on stdin so it can be used as part of a pipeline.

**Comment by mcastorina** [comment]
Thanks for the suggestion! This is already supported by using `-` for the filename:

```bash
cat samples/sine.csv | graph -
```

I'll add it to the help message / docs page.

**Comment by mcastorina** [comment]
Added notes in 49043f3598d63ecd46fe69f27c5ac79b432d0653
