### ISSUE TITLE
Feature request: support resampling with sums and not only with mean

### ISSUE THREAD

**Issue by leighmcculloch** [mcastorina/graph-cli#51]
The resampling option is very convenient, but when resampling data that is counts, it would be ideal to have the option to sum the counts together if the goal is to see total counts over time. 

I think the relevant code is here where mean is used on the resampled data. It'd be great to be able to choose which function is used.

https://github.com/mcastorina/graph-cli/blob/master/graph_cli/graph_cli/graph.py#L156

**Comment by mcastorina** [comment]
Implemented in db889ce5e5c2d59c4a3b7d5d72bec4cf9ea152b5

See `--resample-action` in [OPTIONS.md#line-specific-options](https://github.com/mcastorina/graph-cli/blob/master/OPTIONS.md#line-specific-options)

**Comment by mcastorina** [comment]
Now available in `v0.1.15`
