### ISSUE TITLE
Date formatting

### ISSUE THREAD

**Issue by taq** [mcastorina/graph-cli#56]
I have a CSV file with the following content:

```
"2022-02",1859
"2022-03",27071
"2022-04",5908
"2022-05",3445
"2022-06",3963
"2022-07",1968
"2022-08",12886
```

Not matter what I try, "2022-02" for example always shows as "2022-02-01 00:00:00". Is there a way to make sure data will show exactly as on the file, with no conversion?

**Comment by mcastorina** [comment]
Hm, could you share the command you're using? I just tried with

```
graph test.csv
```

![image](https://user-images.githubusercontent.com/5395814/187044559-5d9b117f-5d77-4940-8a69-4891d2af362f.png)

**Comment by taq** [comment]
Thanks for your answer! The command is:

```
$ graph /tmp/example.csv --bar -o /tmp/example.png --title 'value vs date' --xlabel='date' --ylabel='value' --xtick-fontsize 5 2> /dev/null
```

and produces this image:

![example](https://user-images.githubusercontent.com/9789/187415618-26102c38-22bb-454a-b210-e1f25e3d3c4a.png)

I'm using the Ubuntu version, but I checked the version before sending this issue, and both seems to be `v0.1.18`. Maybe is a good idea install with `pip` and try again?

**Comment by mcastorina** [comment]
Thanks for finding and reporting this bug! I've fixed it in be7742484ba3285cb9f11b9cc5112fc4d0874d7e and released `v0.1.19`. The latest version will be available on pip sooner than the ubuntu repos.

In `v0.1.19`, bar charts will default to not trying to parse the datetime. If you specify `--time-format-input` or `--time-format-output` then it will attempt to parse the time, and `--time-format-output` will behave as expected. For example:

```
graph /tmp/example.csv --bar --time-format-output '~[%m/%Y]~'
```
![image](https://user-images.githubusercontent.com/5395814/188253169-71a7c90a-f11e-4a91-afc9-2b109b55eecd.png)

**Comment by taq** [comment]
You're welcome, thanks for the fix! :-)

**Comment by andrscyv** [comment]
Hi @mcastorina !

First I want to say your tool is awesome, I've used it multiple times.

I'm wondering if there is a way to avoid parsing of a string for a line graph ? 

I have a csv with the following data 

week,deal_count,percentage,date
2023-01-08,3,12.0,ene-08
2023-01-15,3,6.0,ene-15
2023-01-22,12,17.65,ene-22
2023-01-29,6,9.84,ene-29
2023-02-05,2,3.45,feb-05
2023-02-12,4,8.0,feb-12
2023-02-19,4,5.56,feb-19
2023-02-26,4,6.9,feb-26
2023-03-05,2,3.08,mar-05
2023-03-12,7,10.77,mar-12
2023-03-19,8,11.59,mar-19
2023-03-26,3,4.23,mar-26
2023-04-02,3,4.0,abr-02
2023-04-23,2,3.85,abr-23
2023-04-30,1,1.14,abr-30


the date column has the month name in spanish and I wish it would appear as is on the graph but instead I get 
<img width="1019" alt="Screen Shot 2023-05-24 at 15 56 07" src="https://github.com/mcastorina/graph-cli/assets/29495026/c3e44045-745e-4fa9-9b15-446e402b6ee8">
